apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tls-secret
spec:
  secretName: tls-secret
  dnsNames:
    - footestlabel.eastus.cloudapp.azure.com
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
