name: contoso-traders-load-testing

on:
  workflow_dispatch:

env:
  ACA_NAME: tailwind-traders-carts
  ACR_REPOSITORY_NAME: tailwindtradersapicarts
  KV_NAME: tailwindtraderskv
  LOAD_TEST_SERVICE_NAME: tailwind-traders-loadtest
  LOAD_TEST_SERVICE_RESOURCE_GROUP: tailwind-traders-rg
  WEBAPP_NAME: tailwind-traders-carts

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: checkout code
      uses: actions/checkout@v3
    - name: azure login
      uses: azure/login@v1.1
      with:
        creds: ${{ secrets.SERVICEPRINCIPAL }}
    # extract the endpoint url of the aca app from kv
    - name: fetch cartsApiEndpoint
      uses: azure/CLI@v1
      id: fetch-cartsApiEndpoint
      with:
        inlineScript: echo "cartsApiEndpoint"="$(az keyvault secret show --vault-name ${{ env.KV_NAME }}${{ secrets.ENVIRONMENT }} -n cartsApiEndpoint --query "value" -o tsv)" >> $GITHUB_OUTPUT
    - name: load test (carts API)
      uses: Azure/load-testing@v1.1.7
      with:
        # Path of the YAML file. Should be fully qualified path or relative to the default working directory
        loadtestConfigFile: ./tests/loadtests/tailwind-traders-carts.yaml
        loadtestResource: ${{ env.LOAD_TEST_SERVICE_NAME }}${{ secrets.ENVIRONMENT }}
        resourceGroup: ${{ env.LOAD_TEST_SERVICE_RESOURCE_GROUP }}
        env: |
          [
            {
              "name": "domain",
              "value": "${{ steps.fetch-cartsApiEndpoint.outputs.cartsApiEndpoint }}"
            },
            {
              "name": "protocol",
              "value": "https"
            },
            {
              "name": "path",
              "value": "v1/ShoppingCart/loadtest"
            },
            {
              "name": "threads_per_engine",
              "value": "5"
            },
            {
              "name": "ramp_up_time",
              "value": "0"
            },
            {
              "name": "duration_in_sec",
              "value": "120"
            }
          ]
