name: contoso-traders-app-deployment

on:
  workflow_dispatch:
  push:
    branches: ["master"]
    paths:
      [
        "src/TailwindTraders.Api.Carts/**",
        "src/TailwindTraders.Api.Core/**",
        "src/TailwindTraders.Api.Images/**",
        "src/TailwindTraders.Api.Products/**",
        "src/TailwindTraders.Ui.Website/**",
      ]

env:
  ACR_NAME: tailwindtradersacr
  AKS_CLUSTER_NAME: tailwind-traders-aks
  AKS_NODES_RESOURCE_GROUP_NAME: tailwind-traders-aks-nodes-rg
  AKS_SECRET_NAME_ACR_PASSWORD: tailwind-traders-acr-password
  AKS_SECRET_NAME_KV_ENDPOINT: tailwind-traders-kv-endpoint
  CARTS_ACA_NAME: tailwind-traders-carts
  CARTS_ACR_REPOSITORY_NAME: tailwindtradersapicarts
  CDN_PROFILE_NAME: tailwind-traders-cdn
  KV_NAME: tailwindtraderskv
  PRODUCT_DETAILS_CONTAINER_NAME: product-details
  PRODUCT_IMAGES_STORAGE_ACCOUNT_NAME: tailwindtradersimg
  PRODUCT_LIST_CONTAINER_NAME: product-list
  PRODUCTS_ACR_REPOSITORY_NAME: tailwindtradersapiproducts
  PRODUCTS_CDN_ENDPOINT_NAME: tailwind-traders-images
  PRODUCTS_WEBAPP_NAME: tailwind-traders-products
  RESOURCE_GROUP_NAME: tailwind-traders-rg
  UI_CDN_ENDPOINT_NAME: tailwind-traders-ui2
  UI_STORAGE_ACCOUNT_NAME: tailwindtradersui2

jobs:
  deploy-carts-api:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: install dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x
      - name: azure container registry login
        uses: azure/docker-login@v1
        with:
          login-server: ${{ env.ACR_NAME }}${{ secrets.CONTOSOTRADERS_SUFFIX }}.azurecr.io
          username: ${{ env.ACR_NAME }}${{ secrets.CONTOSOTRADERS_SUFFIX }}
          password: ${{ secrets.CONTOSOTRADERS_ACR_PASSWORD }}
      - name: docker build
        run: docker build src -f ./src/TailwindTraders.Api.Carts/Dockerfile -t ${{ env.ACR_NAME }}${{ secrets.CONTOSOTRADERS_SUFFIX }}.azurecr.io/${{ env.CARTS_ACR_REPOSITORY_NAME }}:latest -t ${{ env.ACR_NAME }}${{ secrets.CONTOSOTRADERS_SUFFIX }}.azurecr.io/${{ env.CARTS_ACR_REPOSITORY_NAME }}:${{ github.sha }}
      - name: docker push (to acr)
        run: docker push --all-tags ${{ env.ACR_NAME }}${{ secrets.CONTOSOTRADERS_SUFFIX }}.azurecr.io/${{ env.CARTS_ACR_REPOSITORY_NAME }}
      - name: azure login
        uses: azure/login@v1.1
        with:
          creds: ${{ secrets.CONTOSOTRADERS_TESTING_SERVICEPRINCIPAL }}
      - name: deploy to aca
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp update -n ${{ env.CARTS_ACA_NAME }}${{ secrets.CONTOSOTRADERS_SUFFIX }} -g ${{ env.RESOURCE_GROUP_NAME }} --image ${{ env.ACR_NAME }}${{ secrets.CONTOSOTRADERS_SUFFIX }}.azurecr.io/${{ env.CARTS_ACR_REPOSITORY_NAME }}:${{ github.sha }}

  deploy-products-api:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: azure login
        uses: azure/login@v1.1
        with:
          creds: ${{ secrets.CONTOSOTRADERS_TESTING_SERVICEPRINCIPAL }}
      - name: seed products db
        uses: azure/sql-action@v2
        with:
          connection-string: ${{ secrets.CONTOSOTRADERS_PRODUCTSDB_CONNECTION_STRING }}
          path: ./src/TailwindTraders.Api.Products/Migration/productsdb.sql
      - name: seed product image (product details)
        uses: azure/CLI@v1
        with:
          inlineScript: az storage blob sync --account-name '${{ env.PRODUCT_IMAGES_STORAGE_ACCOUNT_NAME }}${{ secrets.CONTOSOTRADERS_SUFFIX }}' -c '${{ env.PRODUCT_DETAILS_CONTAINER_NAME }}' -s 'src/TailwindTraders.Api.Images/product-details'
      - name: seed product image (product list)
        uses: azure/CLI@v1
        with:
          inlineScript: az storage blob sync --account-name '${{ env.PRODUCT_IMAGES_STORAGE_ACCOUNT_NAME }}${{ secrets.CONTOSOTRADERS_SUFFIX }}' -c '${{ env.PRODUCT_LIST_CONTAINER_NAME }}' -s 'src/TailwindTraders.Api.Images/product-list'
      - name: purge CDN endpoint
        uses: azure/CLI@v1
        with:
          inlineScript: az cdn endpoint purge --no-wait --content-paths '/*' -n '${{ env.PRODUCTS_CDN_ENDPOINT_NAME }}${{ secrets.CONTOSOTRADERS_SUFFIX }}' -g '${{ env.RESOURCE_GROUP_NAME }}' --profile-name '${{ env.CDN_PROFILE_NAME }}${{ secrets.CONTOSOTRADERS_SUFFIX }}'
      - name: azure container registry login
        uses: azure/docker-login@v1
        with:
          login-server: ${{ env.ACR_NAME }}${{ secrets.CONTOSOTRADERS_SUFFIX }}.azurecr.io
          username: ${{ env.ACR_NAME }}${{ secrets.CONTOSOTRADERS_SUFFIX }}
          password: ${{ secrets.CONTOSOTRADERS_ACR_PASSWORD }}
      - name: docker build
        run: docker build src -f ./src/TailwindTraders.Api.Carts/Dockerfile -t ${{ env.ACR_NAME }}${{ secrets.CONTOSOTRADERS_SUFFIX }}.azurecr.io/${{ env.PRODUCTS_ACR_REPOSITORY_NAME }}:latest -t ${{ env.ACR_NAME }}${{ secrets.CONTOSOTRADERS_SUFFIX }}.azurecr.io/${{ env.PRODUCTS_ACR_REPOSITORY_NAME }}:${{ github.sha }}
      - name: docker push (to acr)
        run: docker push --all-tags ${{ env.ACR_NAME }}${{ secrets.CONTOSOTRADERS_SUFFIX }}.azurecr.io/${{ env.PRODUCTS_ACR_REPOSITORY_NAME }}
      # @TODO: This next step really needs to go into the bicep provisioning script
      - name: kv access policy for agentpool managed identity
        uses: azure/CLI@v1
        with:
          inlineScript: az keyvault set-policy --name ${{ env.KV_NAME }}${{ secrets.CONTOSOTRADERS_SUFFIX }} --secret-permissions get list --object-id $(az identity show --name ${{ env.AKS_CLUSTER_NAME }}${{ secrets.CONTOSOTRADERS_SUFFIX }}-agentpool -g ${{ env.AKS_NODES_RESOURCE_GROUP_NAME }} --query "principalId" -o tsv)
      - name: set aks context
        uses: azure/aks-set-context@v3
        with:
          resource-group: ${{ env.RESOURCE_GROUP_NAME }}
          cluster-name: ${{ env.AKS_CLUSTER_NAME }}${{ secrets.CONTOSOTRADERS_SUFFIX }}
      - name: setup kubectl
        uses: azure/setup-kubectl@v3
      - name: create kubernetes secret (acr password)
        uses: Azure/k8s-create-secret@v3.0
        with:
          secret-name: ${{ env.AKS_SECRET_NAME_ACR_PASSWORD }}
          container-registry-url: ${{ env.ACR_NAME }}${{ secrets.CONTOSOTRADERS_SUFFIX }}.azurecr.io
          container-registry-username: ${{ env.ACR_NAME }}${{ secrets.CONTOSOTRADERS_SUFFIX }}
          container-registry-password: ${{ secrets.CONTOSOTRADERS_ACR_PASSWORD }}
      - name: create kubernetes secret (kv endpoint)
        uses: Azure/k8s-create-secret@v3.0
        with:
          secret-type: "generic"
          secret-name: ${{ env.AKS_SECRET_NAME_KV_ENDPOINT }}
          string-data: '{ "${{ env.AKS_SECRET_NAME_KV_ENDPOINT }}" : "https://${{ env.KV_NAME }}${{ secrets.CONTOSOTRADERS_SUFFIX }}.vault.azure.net/" }'
      - name: lint manifest
        uses: azure/k8s-lint@v1
        with:
          manifests: ./src/TailwindTraders.Api.Products/TailwindTraders.Api.Products.yaml
      - name: deploy to aks
        uses: Azure/k8s-deploy@v4
        with:
          manifests: ./src/TailwindTraders.Api.Products/TailwindTraders.Api.Products.yaml
          images: ${{ env.ACR_NAME }}${{ secrets.CONTOSOTRADERS_SUFFIX }}.azurecr.io/${{ env.PRODUCTS_ACR_REPOSITORY_NAME }}:${{ github.sha }}
          imagepullsecrets: ${{ env.AKS_SECRET_NAME_ACR_PASSWORD }}
      # @TODO: REMOVE EVERYTHING BELOW THIS LINE AFTER AKS INTEGRATION IS DONE
      - name: install dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x
      - name: dotnet publish
        run: dotnet publish -o ../Publish/TailwindTraders.Api.Products -c release
        working-directory: src/TailwindTraders.Api.Products
      - name: diagnostic output
        run: ls -la ./src/Publish/TailwindTraders.Api.Products
      - name: deploy to app service
        uses: Azure/webapps-deploy@v2
        with:
          app-name: ${{ env.PRODUCTS_WEBAPP_NAME }}${{ secrets.CONTOSOTRADERS_SUFFIX }}
          package: ./src/Publish/TailwindTraders.Api.Products

  deploy-ui:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: npm install
        run: npm install
        working-directory: src/TailwindTraders.Ui.Website
      - name: npm run build
        run: npm run build
        working-directory: src/TailwindTraders.Ui.Website
      - name: azure login
        uses: azure/login@v1.1
        with:
          creds: ${{ secrets.CONTOSOTRADERS_TESTING_SERVICEPRINCIPAL }}
      - name: deploy to storage
        uses: azure/CLI@v1
        with:
          inlineScript: az storage blob sync --account-name '${{ env.UI_STORAGE_ACCOUNT_NAME }}${{ secrets.CONTOSOTRADERS_SUFFIX }}' -c '$web' -s 'src/TailwindTraders.Ui.Website/build'
      - name: purge CDN endpoint
        uses: azure/CLI@v1
        with:
          inlineScript: az cdn endpoint purge --no-wait --content-paths '/*' -n '${{ env.UI_CDN_ENDPOINT_NAME }}${{ secrets.CONTOSOTRADERS_SUFFIX }}' -g '${{ env.RESOURCE_GROUP_NAME }}' --profile-name '${{ env.CDN_PROFILE_NAME }}${{ secrets.CONTOSOTRADERS_SUFFIX }}'
