name: tailwind-traders-infra-provisioning

on:
  workflow_dispatch:
  push:
    branches: [ "mithun/aca" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: checkout code
      uses: actions/checkout@v3
    - name: azure login
      uses: azure/login@v1.1
      with:
        creds: ${{ secrets.TAILWINDTRADERS_TESTING_SERVICEPRINCIPAL }}
    - name: create resource group
      uses: Azure/arm-deploy@v1.0.8
      with:
        scope: subscription
        region: eastus
        template: ./iac/createResourceGroup.bicep
