name: tailwind-traders-infra-provisioning

on:
  workflow_dispatch:
  push:
    branches: [ "mithun/aca" ]

env:
  SUB_DEPLOYMENT_REGION: eastus2
  RG_DEPLOYMENT_RGNAME: tailwind-traders-rg

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: checkout code
      uses: actions/checkout@v3
    - name: azure login
      uses: azure/login@v1.1
      with:
        creds: ${{ secrets.TAILWINDTRADERS_TESTING_SERVICEPRINCIPAL }}
    - name: create resource group
      uses: Azure/arm-deploy@v1.0.8
      with:
        scope: subscription
        region: ${{ env.SUB_DEPLOYMENT_REGION }}
        template: ./iac/createResourceGroup.bicep
    - name: create resources
      uses: Azure/arm-deploy@v1.0.8
      with:
        scope: resourcegroup
        region: ${{ env.SUB_DEPLOYMENT_REGION }}
        resourceGroupName: ${{ env.RG_DEPLOYMENT_RGNAME }}
        template: ./iac/createResources.bicep
        parameters: ./iac/createResources.parameters.json
