# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
    paths-ignore: [ 'docs/**', '.vscode/**', 'misc/**', 'iac/**', 'readme.md' ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: dotnet publish - 
      run: dotnet publish -o ../Publish/TailwindTraders.Api.Products -c release
      working-directory: src/TailwindTraders.Api.Products
