name: tailwind-traders-carts

on:
  workflow_dispatch:
  push:
    branches: [ 'master', 'mithun/push-to-acr' ]
    paths: [ 'src/TailwindTraders.Api.Carts/**', 'src/TailwindTraders.Api.Core/**' ]

env:
  ACR_NAME: tailwindtradersacr
  ACR_REPOSITORY_NAME: tailwindtradersapicarts
  WEBAPP_NAME: tailwind-traders-carts

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: checkout code
      uses: actions/checkout@v3
    - name: install dotnet
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: azure container registry login
      uses: azure/docker-login@v1
      with:
        login-server: ${{ env.ACR_NAME }}${{ secrets.TAILWINDTRADERS_SUFFIX }}.azurecr.io
        username: ${{ env.ACR_NAME }}${{ secrets.TAILWINDTRADERS_SUFFIX }}
        password: ${{ secrets.TAILWINDTRADERS_ACR_PASSWORD }}
    - name: docker build
      run: docker build src -f ./src/TailwindTraders.Api.Carts/Dockerfile -t ${{ env.ACR_NAME }}${{ secrets.TAILWINDTRADERS_SUFFIX }}.azurecr.io/${{ env.ACR_REPOSITORY_NAME }}:latest -t ${{ env.ACR_NAME }}${{ secrets.TAILWINDTRADERS_SUFFIX }}.azurecr.io/${{ env.ACR_REPOSITORY_NAME }}:${{ github.sha }}
    - name: docker push
      run: docker push ${{ env.ACR_NAME }}${{ secrets.TAILWINDTRADERS_SUFFIX }}.azurecr.io/${{ env.ACR_REPOSITORY_NAME }}:${{ github.sha }}
    # - name: dotnet publish
    #   run: dotnet publish -o ../Publish/TailwindTraders.Api.Carts -c release
    #   working-directory: src/TailwindTraders.Api.Carts
    # - name: azure login
    #   uses: azure/login@v1.1
    #   with:
    #     creds: ${{ secrets.TAILWINDTRADERS_TESTING_SERVICEPRINCIPAL }}
    # - name: diagnostic output
    #   run: ls -la ./src/Publish/TailwindTraders.Api.Carts
    # - name: deploy to app service
    #   uses: Azure/webapps-deploy@v2
    #   with:
    #     app-name: ${{ env.WEBAPP_NAME }}${{ secrets.TAILWINDTRADERS_SUFFIX }}
    #     package: ./src/Publish/TailwindTraders.Api.Carts
